In [116]:
%load_ext autoreload
%autoreload 2

from arm_touchdown import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [117]:
def check_limits(joint_angles, min_constraints, max_constraints):
    if(np.alltrue(joint_angles>min_constraints) and 
       np.alltrue(joint_angles<max_constraints)):
        return True
    else:
        return False

In [118]:
# Run this cell everytime the arm is restarted
rospy.init_node('robot_control_node')

robot_controller = RobotController("Arm_RML", 
                                   ["J1_base", "J2_shoulder", "J3_elbow", 'J4_wrist'], 
                                   "/home/patrick/catkin_ws/src/hebi/arm_control/config/hrdf/anakin.hrdf")
eft = EndEffectorTrajectory(robot_controller)

In [113]:
# eft.target_positions = [
#            [0.03, 0.0, 0.4], # home 
#            [0.03, 0.2, 0.4], # extend
#            [0.03, 0.4, 0.0], # extend and move down
#             [0.0, 0.4, -0.1] 
#             only x,y,z coordinates
#        ]

# Original Constraints
# eft.min_positions = [4, -2*np.pi, -2*np.pi, -np.pi/2]
# eft.max_positions = [5, 2*np.pi, -1, np.pi/2]
            
# eft.min_positions = [4, -2*np.pi, -3.05, -np.pi]
# eft.max_positions = [5, 2*np.pi, -np.pi/4, np.pi]

# eft.get_trajectory(total_duration=40)

# print("------- POSITION ARRAY -------")
# print(eft.positions)
# print("------------------------------\n")


# for t in eft.times:
#    if not check_limits(eft.trajectory.get_state(t)[0], 
#                        np.array(eft.min_positions), 
#                        np.array(eft.max_positions)):
#        print(eft.trajectory.get_state(t)[0])
#        print("Time = ", t)
#        raise ("Joint Angles not within limits!")

In [119]:
eft.positions = np.array([
            [ 4.73091793,  4.89363516,  4.77573206,  4.74393144],
            [-0.02057076,  0.46017654,  1.16832948, -3.78152561],
            [-3.02600002, -2.18277832, -1.97059152, -1.77164562],
            [-1.28942299, -1.28403595, -0.78806982, -5.93687081]
        ])
print(eft.positions)

[[ 4.73091793  4.89363516  4.77573206  4.74393144]
 [-0.02057076  0.46017654  1.16832948 -3.78152561]
 [-3.02600002 -2.18277832 -1.97059152 -1.77164562]
 [-1.28942299 -1.28403595 -0.78806982 -5.93687081]]


In [120]:
eft.get_trajectory(total_duration=20)
print(eft.trajectory.duration)

eft.execute_trajectory()

[ 4.73428154 -0.02085781 -3.03080463 -1.23718262]
20.0
Period: 0.01
-----------
Sending command at time =  20.000000000000327
Current Trajectory State: (array([ 4.74393144, -3.78152561, -1.77164562, -5.93687081]), array([ 0.00000000e+00, -1.99840144e-15,  2.04697370e-16, -4.44089210e-16]), array([-5.20417043e-18, -6.10622664e-16,  4.51028104e-17, -1.11022302e-16]))
Joint angles:  [ 4.75630474  0.96909362 -2.0831356  -1.17956161]
[INFO] [1707183167.091612]: Staying in the last position for 5 seconds...


In [76]:
eft.trajectory.get_state(35)

(array([ 4.7414745 , -3.08627016, -1.81015301, -5.23121537]),
 array([ 0.00072405, -0.35004158,  0.01848502, -0.35659696]),
 array([ 0.0002495 ,  0.08992833, -0.00400027,  0.09272972]))

In [ ]:
# Working IK Values

------ POSITION ARRAY -------
[[ 4.73091793  4.89363516  4.77573206  4.74393144]
 [-0.02057076  0.46017654  1.16832948 -3.78152561]
 [-3.02600002 -2.18277832 -1.97059152 -1.77164562]
 [-2.28942299 -1.28403595 -0.78806982 -5.93687081]]
------------------------------